### ISSUE TITLE
config null check

### ISSUE THREAD

**Issue by geroyche** [networknt/light-codegen#100]
You're null checking model before calling isUrl on it, you're not doing the same with config.

https://github.com/networknt/light-codegen/blob/master/codegen-cli/src/main/java/com/networknt/codegen/Cli.java#L70

**Comment by stevehu** [comment]
@geroyche Thanks for the catch. This will be fixed once I have access to my computer.

**Comment by stevehu** [comment]
@geroyche I have made the update to check config. Could you please review? Thanks a lot for your help.

**Comment by geroyche** [comment]
looks good! feel free to close the issue as you see fit (not sure about your workflow, whether I should close now)

**Comment by stevehu** [comment]
@geroyche Thanks for your review. There is no formal workflow as of yet :)
