### ISSUE TITLE
Light-codegen usage pattern

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-codegen#103]
Hi Steve,

I've had a good chance to think about the usage pattern of light-codegen and was hoping you could help me understand the expectation.

This comes mostly from trying to understand why i don't come back to using this functionality when starting out a new api, and instead turn to simply building off of a base example and expanding on it. I understand the many reasons why it could be bad idea to do that, but from my end at least it seems easier then writing a swagger/openapi spec.

When starting a new api from scratch it is likely that I am not quite tied down to a specific interface, as in general the idea is not yet fully formed. So focusing the start of my work on generating a document that I know for a fact will change is not very tempting. In the following stage, when i'm partly through implementation and i realize that I will need to change the interface, i now have to update both the source and the spec (if I'm being a good citizen) which leads itself to human error if one forgets.

Is this the expectation for how it will be used in practice? Or is there something fundamental i'm missing?

This question did lead me to investigate the type of codegen/automation that i would be most likely to leverage.. i'm not sure if something like it exists (or if it should) but might just be personal preference.

There are 2 things i would like most:
1. CLI similar to yeoman:
	- Questions and responses allow you to specify the features to include, the name/metadata of your app, which build tool to leverage, etc..
	- If published as an npm package it can be easily used as a global command so we wouldn't need to clone the source in order to use it and it could be used from any directory easily.
2. Automated generation of swagger/openapi spec via annotations (like https://github.com/swagger-api/swagger-core/wiki/Annotations-2.X). So instead of using the spec to build your code, 
your code will build the spec. This is primarily the lazy developer in me speaking, but maintaining my code and the spec at the same time for any changes could be tedious.

Looking forward to your feedback!

**Comment by stevehu** [comment]
@NicholasAzar Design First is something we are encouraging for our clients and so far it generated a lot of positive feedback. It is a very important topic and I don't want to treat it lightly. So I have written an article to list pros and cons. Also it gives my opinion on when we should use Design First and when we should use Code First. Please review the article and let me know what do you think. 

https://doc.networknt.com/design/design-first/

Regarding to the CLI, I agree with you that we should have a similar interface like yeoman and even thinking to rewrite all our tool in Rust as normal Linux command line utilities.

**Comment by NicholasAzar** [comment]
That was a very informative article and I really appreciate you spending your time putting it together, as I do agree this is an important topic.

I don't see coding first as mutually exclusive to designing first, but rather a means to write the design using a language (likely) more widely known. I don't want to confuse my point to mean implement before designing, if we can simply write a method header with annotations and generate the contract. Almost all the principles of designing first would be kept, but the language used to generate the design would be changed.

There's one point that I don't yet see addressed, which is the evolution and maintenance pattern of the api... If the API is fully (or partially) implemented and changes come in via contract update, how is this supposed to be handled? Is the api regenerated and diffed with the implemented base via manual process? (I'm thinking more along the lines of a change to an unpublished api, for an issue maybe found in testing.. not a change on a production api that would be handled via version increased and phased migration)

With this all said however, you do have many great points that left me without an answer other then your own. Namely the consumer driven design notion, as all my requests come from having the same person be designing and implementing. The solution you currently have is critically important when the developers aren't the ones handling requirements.

Rust is not yet at the top of my list of tech I want to dive into... although it is certainly on the list. I was actually hoping in the next few days to take a deeper dive into gradle.. as soon as I can find some time.. :smiley:

**Comment by stevehu** [comment]
service evolution is a very important topic and most people have even realized how important it is until they have hundreds or thousands services on production. I have written something long time ago about this topic. Please review and let me know if there are something to be add/update/delete. Thanks.

https://doc.networknt.com/design/evolution/

**Comment by stevehu** [comment]
In DGP project, @chenyan71 has added a maven plugin to generate code on the fly after changing the specification. He is also working on the component generation from POJO now. 

https://doc.networknt.com/tutorial/generator/codegen-maven/

**Comment by ddobrin** [comment]
I am adding some additional features.

My client has scripting to regenerate all their APIs with every framework upgrade and several issues have been found. It makes updates easier and with a number of upcoming changes, it will make contract-driven-design easier.
