### ISSUE TITLE
Light Codegen Web with express server

### ISSUE THREAD

**Issue by auahmed** [networknt/light-codegen#138]
Hi,

I needed some help using the codegen web and anything will be greatly appreciated.
I was able to use the codegen web and viewer that is provided in networknt project successfully but since was brining the service inside another application i was going to have a different UI and had another server which contacted the codegen service.

I have provided a sample server on a public repo and can be obtained by:
````
git clone git@github.com:auahmed/test-server.git
````

I know on my sample one i am not passing anything under model and config but i tested out using postman and was still able to get a zip file back and unzip it successfully (file size matched the below content-length key - 24162).
The issue i am getting originally is that i cannot unzip the file. 
I noticed that the length of my data received back was different then what was being sent by the server and the content-length in the header. while in the view of codegen web is the same.
Why it is being different i cannot figure it out and was wondering if you might have come across a similar situation before. 

steps to test:
````
npm install
node app.js
curl http://localhost:9000
````

response:
````
########### HEADERS:  { connection: 'close',
  server: 'L',
  'content-type': 'application/zip',
  'content-length': '24162',
  'content-disposition': 'attachment',
  date: 'Sun, 08 Apr 2018 16:48:47 GMT' }
########### AXIOS:  23390
````
As seen above the data.length is less then the actual content-length when it should have been the same to have a successful zip file built.

Thanks,

**Comment by stevehu** [comment]
As you are working on a single page application, why not just call the codegen-web service directly from your SPA? The only thing you need to do is to add cors handler in the codegen-web service if it is not configured yet. In the long run, we might need to integrate more light-portal services and I would recommend using these services directly from React.js

**Comment by auahmed** [comment]
its not a single page application. Its the marketplace and what we were doing with it was having the UI make the calls to the server which will then route it to the various API's that need to be contacted.
In the example i had provided i had just made a new server to show an example.

It is still possible to make the call directly from the application but i will get an error due to the missing cors handler but that can be fixed if we go that route. was just seeing if i could have kept it consistent like all the other API calls the application was making. 
just couldn't figure out why the same method that works in the codegen-web project doesnt work in express server so i guess it was bothering me.

**Comment by stevehu** [comment]
As we've discussed, I have enabled CORS handler in codegen-web. You can use the service directly from your SPA. Let me know if you have issues. Thanks. 

https://github.com/networknt/light-codegen/issues/139

**Comment by auahmed** [comment]
thanks steve!

**Comment by auahmed** [comment]
If we are using cors am i supposed to send something specific from the request headers?
i had sent a request and gotten the following on my server:
````
20:39:23.194 [XNIO-1 task-1]  7W701w0YTwm-VwGscsAHcA DEBUG com.networknt.cors.CorsUtil matchOrigin - Request rejected due to HOST/ORIGIN mis-match.
````

**Comment by stevehu** [comment]
What is your server express server url? I thought you are using http://localhost:3000.

**Comment by auahmed** [comment]
i was using http://localhost:3001.
I checked in the config files for the cors and it allows from origin localhost.

**Comment by stevehu** [comment]
@auahmed I have changed the port to 3001 as default. You can also externalize the config files to change the cors.yml for your environment.

**Comment by auahmed** [comment]
@stevehu Thanks Steve, that did the trick
