### ISSUE TITLE
code generation fails from openapi/swagger yaml files

### ISSUE THREAD

**Issue by b-gyula** [networknt/light-codegen#145]
Given a *yaml* file as *model* parameter ClassCastException occurs:

java.lang.ClassCastException: java.base/java.lang.String cannot be cast to com.jsoniter.any.Any
        at com.networknt.codegen.rest.OpenApiGenerator.injectEndpoints(OpenApiGenerator.java:353)
        at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:141)
        at com.networknt.codegen.Cli.run(Cli.java:98)
        at com.networknt.codegen.Cli.main(Cli.java:50)
1. *com.networknt.codegen.rest.OpenApiGenerator#injectEndpoints* shall not treat the *model* parameter as *Any*

**Comment by stevehu** [comment]
@b-gyula Is it possible for you to send me the OpenAPI Specification? The OpenAPI spec is very flexible, and chances are there are some elements missing or not handled correctly. Thanks.

**Comment by b-gyula** [comment]
It's not a specific OpenAPI specification. **_OpenAPI YAML file format is not supported at all_**. There are number of places in the code trying to read the model as JSON directly. yaml format is treated as simple *String*. Beside the one I've mentioned for example all these cast fail:
*com.networknt.codegen.rest.OpenApiGenerator#generate (line 149)*
`Any anyComponents = ((Any)model).get("components")`

**Comment by stevehu** [comment]
Jackson can load YAML file as well and it should be easy to add it. Internally, it is still parsed as JSON though. I didn't support it in the initial release just due to limited time.

**Comment by b-gyula** [comment]
From the comments in the code I had the assumption, it supports yaml format, that's why I started the investigation. I wish to be implemented, because converting the OpenAPI definition to json is cumbersome. 
I see it would not be a big change either. I'm evaluating the framework, to be used in a production application, if it's as easy to use as quick it is in the benchmarks, I might offer my help to implement the yaml support.

**Comment by stevehu** [comment]
It is great if you could help. Most often, we are dealing with large enterprises and they have separate YAML files that need to be bundled together into a final JSON file. The following link is a utility to handle Swagger 2.0 specs. We are having some trouble to separate OpenAPI 3.0 specs as the new swagger-editor doesn't support multiple files. 

https://github.com/networknt/swagger-bundler

**Comment by ddobrin** [comment]
This issue can be closed at this time, as the tooling (codegen, bundler) have all been updated

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [code generation fails from openapi/swagger yaml files](https://trello.com/c/RdHIKUeg/94-code-generation-fails-from-openapi-swagger-yaml-files)
