### ISSUE TITLE
Binary Content

### ISSUE THREAD

**Issue by cbehrenberg** [networknt/light-codegen#158]
Hello,
I believe the treatment of binary content is not right for type generation.

According to [https://swagger.io/docs/specification/describing-responses/#response-that-returns-a-file](https://swagger.io/docs/specification/describing-responses/#response-that-returns-a-file) you can specify with type: string + format: binary a byte array (like byte[]) and with type: string + format: byte base64 encoded byte content.

However, in both cases, a String object is generated for me (which is not correct for me, I expect byte[]). When I use Swagger Editor and generate a Java Client, however, a byte array is created (which looks correct to me).

I believe it is related to the typeMapping in class SwaggerGenerator, as it generates byte[] only if type == "ByteArray" or "binary" in my OpenAPI spec. I tested it - it generates byte[]. However, this violates OpenAPI spec and the editor goes nuts...

Can you please verify?

**Comment by stevehu** [comment]
@cbehrenberg Thanks for bringing it up. This is the very first use case that we need to generate a model that represents a file. I am wondering if you have any example specification that can be shared so that we can get the issue fixed. Thanks a lot for your help.

**Comment by stevehu** [comment]
Have heard anything from the original issue opener. Close it.

**Comment by 243826** [comment]
could we open it back... it's an issue I faced as well. I was about to open another issue.

**Comment by stevehu** [comment]
Just reopened it. It would be great if you have a use case and example specification.

**Comment by 243826** [comment]
@cbehrenberg if you still care about this, could you check if this issue is resolved to your satisfaction?

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Binary Content](https://trello.com/c/baMRavc0/114-binary-content)
