### ISSUE TITLE
overwriteHandler=false does not create new handlers

### ISSUE THREAD

**Issue by siom79** [networknt/light-codegen#164]
I have created a first version of my service and implemented the stubs generated by light-codegen. Now I want to add a new ``path`` to my openapi specification. Hence, I run ``light-codegen`` with the option ``overwriteHandler`` set to ``false`` in order to avoid losing my changes on the existing handlers.

I expected that the new handler gets created, but it is not.

Once I set ``overwriteHandler``to ``true``, the new handler is created but I lose all my changes of the existing handlers.

**Comment by ddobrin** [comment]
When the overwrite flag is set to false, it does not generate the handlers in the *.handler.* package of your choice.
This is a valid point, Martin

**Comment by stevehu** [comment]
@siom79 The generator is stateless and it doesn't know how many handlers have been generated before to decide if a new handler is added. The only option for us is to check if the file exists in the generator. I will open an issue to address it. Meanwhile, you can regenerate the code to a separate folder and do a full-text comparison.

**Comment by stevehu** [comment]
@siom79 @ddobrin Please review the changes under #165. Thanks.
