### ISSUE TITLE
OpenAPI spec Reusable Enums not supported

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-codegen#176]
From the looks of it, the codegen doesn't currently support generating Reusable Enums per openapi specification outlined here: 
https://swagger.io/docs/specification/data-models/enums/

Is there any plan to implement this?

**Comment by stevehu** [comment]
Currently, enums are generated inline within the parent class. It should be very easy to make the change to generate a separate enum file from components. In the OpenAPI generator, we have access to the openapi-parser API and it would be very easy to generate classes based on the json overlay object. Do you want to take a look at it?

**Comment by NicholasAzar** [comment]
Thank you @auahmed !!
