### ISSUE TITLE
got error on generated handler test case

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#179]
ClientRequest request = new ClientRequest().setPath("/api/v1/goals/goalId").setMethod(Methods.get);

should be:

Methods.GET

**Comment by chenyan71** [comment]
Same for post as well

            ClientRequest request = new ClientRequest().setPath("/api/v1/goals").setMethod(Methods.post);

**Comment by stevehu** [comment]
This is a newly introduced defect in release 1.5.19. It wasn't detected as the generated test case body is commented out.
