### ISSUE TITLE
Unable to divide main yaml file into separate yamls

### ISSUE THREAD

**Issue by agiroshanark** [networknt/light-codegen#181]
I would like if it possible to separate out definitions and schemas into separate yaml files.
Example:-
schemas:
          Pet:
          $ref: '/definitions/petDefinitions.yaml#/components/Pet'

**Comment by stevehu** [comment]
@agiroshanark supporting multiple local files in OpenAPI 3.0 is a little bit tricky as JSON schema reference is a URI. light-codegen can work with a remote specification file which can refer to other schemas; however, all the schemas must be available online. We are working on the light-portal now and it can hold specifications online after publishing to it. Meanwhile, the best solution would be creating a bunlder for OpenAPI 3.0 just like this project https://github.com/networknt/swagger-bundler

```
java -jar codegen-cli/target/codegen-cli.jar -f openapi -o /tmp/openapi-petstore -m https://raw.githubusercontent.com/networknt/model-config/master/rest/openapi/petstore/1.0.0/openapi.json -c https://raw.githubusercontent.com/networknt/model-config/master/rest/openapi/petstore/1.0.0/config.json
```

**Comment by ddobrin** [comment]
@agiroshanark: 
A new bundler version for OpenAPI will be available in the next few days in the networknt organization, in max a week.

It has already been tested in a large organization with multiple dependent files and totalling over 10K lines of OpenAPI specs. It outputs bundled files in both JSON and YAML

Codegen works easily afterwards as per Steve's prev comment.

This issue will be closed when the OpenAPI bundler is released.

**Comment by ddobrin** [comment]
@agiroshanark : The openapi-bundler addresses this issue.
To assist you further, a sample of embedding a larger number of dependent YAML files into one OpenAPI spec file will be provided in the openapi-bundler soon.

Please see this link: https://github.com/networknt/openapi-bundler

I will be closing this issue at this time
