### ISSUE TITLE
Exception thrown if servers not specified in openapi definition

### ISSUE THREAD

**Issue by zabooma** [networknt/light-codegen#184]
If servers section is omitted from openapi (or it is there but url is not defined) codegen/openapi throws an exception. This section should be optional if the base path is empty and codegen should be able to handle it.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exception thrown if servers not specified in openapi definition](https://trello.com/c/W3KoNXJb/24-exception-thrown-if-servers-not-specified-in-openapi-definition)
