### ISSUE TITLE
Two way sync between OpenAPI spec and Code in maven plugin

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#197]
This issue was raised from the Gitter and I think it is not hard to do for the model at lease. Put it into the backlog. 

For ideas of improving Light-codegen Maven plugin applied for Code-first approach, please upgrade new features about 2-way Sync between OpenApi Spec config file and Current API endpoint including new-in-programming functions. Let's say that most developers are not professional, and many API projects are not perfectly designed from the beginning. Light-4j or Light-rest-4j should, as my vision, support flexible design and programming method like Agile mindset, or similar to automatic tools for synchronizing working java source code with Swagger/OpenAPI Spec (most famous is Spring Boot with JHipster). You should please improve lightCodeGen plugin more easy-to-use than that in Perstore-with-codegen sample. What I mean is In one Maven project you Light-codegen plugin can detect new API endpoint functions with the new data structure and sync with openapi.yaml/json file before release building.

**Comment by PeterKieu** [comment]
Spring Boot guys love this feature! Hope to see it soon. Thanks

**Comment by chenyan71** [comment]
We can start from model reverse generation first. Sometimes when service API project start, development team will start from data model or generate data model from class diagram. 

In this case, we can add new feature to generate model openapi yml file from existing class model. And then use openapi-bundler to merge it to  main spec which has endpoints defined inside.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add openAPI spec generator](https://trello.com/c/f01sNYyN/179-add-openapi-spec-generator)
