### ISSUE TITLE
Add new functionality and updated config.json with new parameters

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-codegen#200]
1. ability to generate model only
2. ability to bypass the model regeneration
3. ability to generate code using arbitrary names for the generation config file, as well as the specification file

**Comment by ddobrin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add new functionality and updated config.json with a model generation only option; it is an optional flag default to false](https://trello.com/c/kj5EC9Wf/58-add-new-functionality-and-updated-configjson-with-a-model-generation-only-option-it-is-an-optional-flag-default-to-false)

**Comment by NicholasAzar** [comment]
Hi @ddobrin , was there an associated change to the documentation to help with discovery of this new feature?

**Comment by ddobrin** [comment]
Hi @NicholasAzar : there will be an update to the documentation.

There were 2 showstoppers which had to be addressed first and have been committed last night and today.

Documentation will follow for the config.json
