### ISSUE TITLE
Web based generator API will output zip file content instead of zip file url for SPA

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#21]
After generation, the target folder will be zipped and the content will be sent to the consumer directly instead of url to download the zip file.

**Comment by NicholasAzar** [comment]
Hi @stevehu , been having a fair bit of trouble getting this to work on my own. I've tried multiple ways of returning the zip, but from the front end code I haven't been able to generate the zip in completeness (got all the folders in the zip generated, but no files...). Would you have a chance to help point me in the right direction?

**Comment by stevehu** [comment]
This is actually my issue. That feature is only half baked and I could not focus on it lately. I will look into it this weekend. Thanks for pointing it out.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Web based generator API will output zip file content instead of zip file url for SPA](https://trello.com/c/K15e4BRt/207-web-based-generator-api-will-output-zip-file-content-instead-of-zip-file-url-for-spa)

**Comment by stevehu** [comment]
This has been resolved for a while already.
