### ISSUE TITLE
Generate config file for each handler wired into the handler chain 

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-codegen#216]
This is issue [1] in the document:
https://github.com/networknt/light-rfcs/blob/master/light-codegen/0004-code-generation-with-env-values-support.md

**Comment by dz-1** [comment]
@stevehu 
I have two questions regarding this change:
1. There are three possible ways to generate the default config files for handlers:
1) copy the default config files into codegen and use them as templates to generated the required one. 
    Using this approach, we have to make sure the config files are in sync between the codegen project and the handlers' projects.

2) add the handers' projects into the pom files of the codegen project. 
     This way, we'll introduce a whole bunch of dependencies into the codegen tool.

3) let the users/developers to specify a classpath which can be used to load the handler classes and default configuration files.
    This way, we may not be able to find 'classnotfound' issues at compile time.

Please advise which approach you prefer or suggest a better solution.

2. Another question is about the default values within the config files. If the value is an array, how should we specify the keys and default values. Please advise.

**Comment by stevehu** [comment]
@dz-1 The ultimate goal for us is to allow users to inject their own handlers in the codegen so that they can add handlers to address cross-cutting concerns within the business context without customized the light-codegen. With this in mind, I think it makes sense to externalize the config files for handlers to another location. Other externalized information might include the package for the customized handler and pom info as well. Given the limited time for this release, I think we can just hardcoded config templates to make it work. It is your option 1 and the most simple approach. 

For the second question, can you have a chat with @jiachen1120 as he implemented the array and map for the value injection? The only config file that I can think of is the service.yml and how it is handled is depending on the injection logic. @NicholasAzar @ddobrin, what do you think?

**Comment by ddobrin** [comment]
Guys,
**_for the first question:_**
[1]the codegen itself requires to have the ability to configure different templates and different versions 👍 

For ex: Master branch caters to the current light-4j/light-rest-4j/etc release, while the develop branch caters to the N+1 version.
While bringing in enhancements or fixing errors, it is beneficial to be able to allow for an externalized location of the template files.

[2] clients, such as mine right now, have developed an API testing framework, which they'd like to inject automatically upon generation of a large number of APIs. 
This externalization is something they have been asking for and issue #160 has been created for this purpose back in July '18

It makes sense to have it there.

Simple approaches used are changing the pom.xml and then passing in the externalized folder to the light-codegen build, simple, but makes you build a custom light-codegen.

The other is based on #225 and definitely an improvement.

If you are thinking of hard-coding the files for the default handler.yml, as it stands today, and have 1:1 handler mapping to a config file, it works for this release, as users wish to put it to work.
The ext release can address it, as clients have quite elaborate handler lists at this time.

**_For the second question_**, when generating default values, I think that injecting, at this time, and this release, a map/list, is something which can be left for the following release.

The effort, for larger groups with many APIs, is parameterizing 25-35 services, rather than just the map/list injection. Practically, it would make sense to me given the short timeframe

**Comment by jiachen1120** [comment]
**For the second question,** Currently, only string and primitive type of value can be defined inside curly braces as the default value, but list and map can be injected by using values.yml.

So, in my opinion. Maybe we can generate in the following way.

For string and primitive value
Simply convert key:value to key: ${moduleName.key:value}

For List and Map
Convert key:(map or list) to ${moduleName.key} without default value inside braces and instead store the default value into values.yml

For example, convert service.yml 
```
singletons:
- com.networknt.registry.Registry:
    - com.networknt.consul.ConsulRegistry
```

to 

```
singletons: ${service.singletons}
```
and include the default value into values.yml
```
service.singletons:
- com.networknt.registry.Registry:
    - com.networknt.consul.ConsulRegistry
```
 
The backward is we need to put a lot of lines into values.yml and the values.yml would look a little bit messy. However, putting list and map inside curly braces if suppose it is possible, would look worse. @dz-1 @stevehu @ddobrin @NicholasAzar Look forward to your opinion!

**Comment by stevehu** [comment]
@jiachen1120 Thanks for the detailed explanation for the list and map injection. This is better than I thought as it provides more flexibility for the users. For example, adding customized handlers to the handlers list etc.

**Comment by ddobrin** [comment]
@jiachen1120 this will work even better when we get to solve also the #160 and #225 issues.

we can document in the values.yml sections which Development teams might wish to customize and others which Ops team will.

ex.: {singletons} would be set by the Development teams, while changing ports or usernames/passwords rests with Ops Teams moving a service across test phases.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generate config file for each handler wired into the handler chain](https://trello.com/c/g7c2loxC/85-generate-config-file-for-each-handler-wired-into-the-handler-chain)
