### ISSUE TITLE
Generate environment-based variables or plain default values, via flag

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-codegen#217]
This is issue [2] in the document:
https://github.com/networknt/light-rfcs/blob/master/light-codegen/0004-code-generation-with-env-values-support.md

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generate environment-based variables or plain default values, via flag](https://trello.com/c/3itQCmd3/84-generate-environment-based-variables-or-plain-default-values-via-flag)
