### ISSUE TITLE
change codegen to not re-generate TestServer class if config value specChangeCodeReGenOnly is true

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#227]
1. change codegen to not re-generate TestServer class if config value specChangeCodeReGenOnly is true;

2. Change TestServer template for code quality
   -- set private constructor before any public methods

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [change codegen to not re-generate TestServer class if config value specChangeCodeReGenOnly is true](https://trello.com/c/NBVYzHAo/81-change-codegen-to-not-re-generate-testserver-class-if-config-value-specchangecoderegenonly-is-true)
