### ISSUE TITLE
Reference type error results in non compiling code

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-codegen#234]
The name where the model generation for the types is suppressed but the types are not replaced with their corresponding primitive boxed types or array types. It results in non-compiling code.

e.g. I had  schemas
```
"UserId": {
  "type": "string",
   "minLength" : 8,
   "maxLength: 32
},
"Pair": {
  "type": "object",
  "required": [
      "primary",
      "secondary"
  ],
  "properties": {
     "primary" : {
        "$ref" : "#/components/schemas/UserId"
      },
     "secondary" : {
        "$ref" : "#/components/schemas/UserId"
      }
  }
}
```

I would get the following model for ```Pair```
```
class Pair {
  UserId primary;
  UserId secondary;
  
  // irrelevant details deleted
}
```

but will not get the model for ```UserId```. Obviously the code would not compile.

_Originally posted by @243826 in https://github.com/networknt/light-codegen/pull/204#issuecomment-466625860_

**Comment by jiachen1120** [comment]
All property's types start with `$ref` will be set to its own name. This is incorrect and should be replaced with the type it references.

The above specification should generate the following code
```
class Pair {
  String primary;
  String secondary;
  
  // irrelevant details deleted
}
```

**Comment by 243826** [comment]
I ended up modifying the code in the light-codegen a bit and have a solution which I think is not fully backed but is better than the current situation. should I create a PR?

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reference type error results in non compiling code](https://trello.com/c/d0zH0mIa/113-reference-type-error-results-in-non-compiling-code)
