### ISSUE TITLE
Uncompilable code generation caused by invalid variable name

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-codegen#236]
Related Jira ticket: API-73

The following specification would cause uncompilable code generation.

**1**. using the lowercase prefix string as the model name:
```
"paymentBaseType": {
 ...
}
```
error codes:
```
private paymentBaseType paymentBaseType;
...
List<paymentBaseType>
```
The prefix for the name of the POJO class generated according to this specification is automatically converted to uppercase. However, when referring to a type, the prefix of the type is not converted to uppercase. So causing a mismatch.

Solution: convert the type's prefix to uppercase 

**2**. using invalid character as enum element name (number, "/", "+"...)
```
"frequency": {
"type": "int",
"enum": [1, 2, 3]
```
error codes
```
1 ("1"),
        
2 ("2"),
        
3 ("3"),
```
The names of each element should conform to the naming convention of java variables.

Solution: convert to a valid variable name, for example, prefix with "_" or replace the invalid character with "_"

**3**. Using java keywords as variable name (new, public ...)
Solution: convert the prefix to uppercase

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Uncompilable code generation caused by invalid variable name](https://trello.com/c/uS0kCIhy/112-uncompilable-code-generation-caused-by-invalid-variable-name)
