### ISSUE TITLE
Make pom.xml developer friendly by seggragating shading, javadoc, sources into a non-default profile

### ISSUE THREAD

**Issue by 243826** [networknt/light-codegen#242]
While developing, every time I compile the code, precious time is spent in shading, building additional artifacts (sources, javadoc) which typically are a must when it comes to deploy the code. Doing these steps during development come just in the way of productivity.

Would be nice if they are segregated into a different profile which needs to be activated by passing a special flag.

**Comment by 243826** [comment]
Also create the dependency-reduced-pom.xml in the target folder instead of the project folder.

**Comment by stevehu** [comment]
@243826 It is always a good idea to have multiple profiles to control how to build. We have just too busy to get things done :) For most of us, we are using light-bot to sync and build locally while doing something else, so it is not a crucial feature but definitely nice to have.

**Comment by stevehu** [comment]
Agreed. Frankly, I don't even know how to make that file into the target. We have to put it into the .gitignore to avoid checking it into the git. It would be fantastic to move it to the target.

**Comment by 243826** [comment]
ok... i'll submit the PR to address the issues I listed here.

**Comment by stevehu** [comment]
Thanks a lot.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make pom.xml developer friendly by seggragating shading, javadoc, sources into a non-default profile](https://trello.com/c/XvPkcNHf/111-make-pomxml-developer-friendly-by-seggragating-shading-javadoc-sources-into-a-non-default-profile)
