### ISSUE TITLE
Add new config parameter for user to config if the pom file should be regenerated or not

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#287]
When user use maven plugin to execute light-codegen, the pom file shouldn't be override.

Add new config parameter to make pom file override to be optional

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add new config parameter for user to config if the pom file should be regenerated or not](https://trello.com/c/e8Hn7ULf/196-add-new-config-parameter-for-user-to-config-if-the-pom-file-should-be-regenerated-or-not)

**Comment by stevehu** [comment]
This is not backward compatible as all existing config.json are not anymore and the new project won't have the pom.xml generated.
