### ISSUE TITLE
Codegen support for decryption method

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-codegen#296]
When code is generated from codegen it currently doesn't allow developers to provide which type of decryption they want to use. We should let developers decide if they want default, environment, or stdin options and generate the config.yml appropriately.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Codegen support for decryption method](https://trello.com/c/QJRSunVu/214-codegen-support-for-decryption-method)
