### ISSUE TITLE
generate deployment.yml for kubernetes deployment

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#299]
To generate a Kubernetes config file for deploying and creating a service.
Do I need to add a config to enable/disable this feature or I can just generate it by default just like the Dockerfile? @stevehu

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [generate deployment.yml for kubernetes deployment](https://trello.com/c/fZSGe91R/271-generate-deploymentyml-for-kubernetes-deployment)
