### ISSUE TITLE
The debug agent in exec-maven prevents from starting multiple tasks

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#328]
The dev friendly profile we added significantly reduced the time for debugging; however, I found one small issue when starting multiple services on the same machine with exec:exec. Only one of the server can be started even though they are not binding to the same port. 

```
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [:735]
[ERROR] Command execution failed.
```
With investigation, I found that we are using a debug agent in the exec-maven task. I am wondering if we can remove the JDWP as I don't think anybody is doing remote debugging because the light-4j application is just a plain POJO. @243826 Could you please provide your comment on it? 

```
        <profile>
            <id>debug</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <java.debug.argument>-Xdebug</java.debug.argument>
                <java.debug.agent>-Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n</java.debug.agent>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${version.exec-maven}</version>
                        <configuration>
                            <workingDirectory>${project.build.directory}</workingDirectory>
                            <executable>java</executable>
                            <arguments>
                                <argument>-cp</argument>
                                <classpath />
                                <argument>${java.debug.argument}</argument>
                                <argument>${java.debug.agent}</argument>
                                <argument>${project.main.class}</argument>
                            </arguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

```

**Comment by ddobrin** [comment]
None of the developers at my client is using remote debugging; they just start the server and stop it in their endpoint handler or the XCC they are working on at that time.

**Comment by stevehu** [comment]
Although we might not need remote debugging for the standalone application, there are certain cases that we need to debug into the container. Sometimes, an application work perfectly OK in as a standalone process, or in an IDE; however, once it is Dockerized, it stops working. Normally, this is related to the docker network, but it would be great if we can debug remote application inside a Docker container. Furthermore, when an application is running in Kubernetes or Openshift cluster, we can leverage squash (https://github.com/solo-io/squash) for remote debugging.

**Comment by stevehu** [comment]
In order to make sure that we can start several services on the same machine, we are going to remove the exec debug agent. To support container remote debugging, I am going to provide a Dockerfile-Debug with the debug agent wire in. I am going to write a tutorial for the container debugging as well.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The debug agent in exec-maven prevents from starting multiple tasks](https://trello.com/c/aDIhKI0R/277-the-debug-agent-in-exec-maven-prevents-from-starting-multiple-tasks)
