### ISSUE TITLE
add logback appender for package defined in config

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#329]
create an appender in logback.xml with the package defined in codegen config, so that they can control the log level of their own code.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add logback appender for package defined in config](https://trello.com/c/Kyec42iE/312-add-logback-appender-for-package-defined-in-config)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add logback appender for package defined in config](https://trello.com/c/EnG2feNp/313-add-logback-appender-for-package-defined-in-config)
