### ISSUE TITLE
Why Java11 in release?

### ISSUE THREAD

**Issue by 243826** [networknt/light-codegen#331]
Hi,

  I am wondering if Java11 on the release branch was intentional. If so, what about support for Java 1.8?

--
Thanks,
Chetan

**Comment by stevehu** [comment]
@243826 I have posted on the Gitter for the reasons. Let me know if you still have questions after reading it. 

https://gitter.im/networknt/light-4j

**Comment by 243826** [comment]
makes sense.

Does this mean we have to make 2 PRs - one for master and the other one for 1.6.x?

**Comment by stevehu** [comment]
In most case, there is no need. I have sync the code between master and 1.6.x and they are almost identical. We just need to merge into the master branch first and then cherry pick to the 1.6.x if the PR is bug fixes or resolve a security vulnerability.

**Comment by 243826** [comment]
I have created PR for both the branches for a bug fix. Please
review/approve/merge in whichever order. Thanks.
