### ISSUE TITLE
find a way to build smaller docker image with jdk11 and jlink

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#333]
The current Dockerfile in the generator is using the 11-slim but it is still too big. Need to find a way to reduce the size of the images. Alpine is available only with AdoptOpenJDK and it is not TCK certified.

**Comment by lanphan** [comment]
Hi,
I think you can give distroless java a try.
1 reference link abt advantage of distroless images: https://medium.com/@dwdraju/distroless-is-for-security-if-not-for-size-6eac789f695f

**Comment by stevehu** [comment]
@lanphan This is an interesting base image; however, we might need to wait for a while for the jdk11 to be stable. There are still some open issues. https://github.com/GoogleContainerTools/distroless/tree/master/java

What I am thinking is to provide multiple Dockerfiles for different base images and let users choose which one to use.

**Comment by stevehu** [comment]
This is the final version that we are using for the jdk11. So far, it works pretty well. 

https://github.com/networknt/light-router/blob/master/docker/Dockerfile
