### ISSUE TITLE
Output generator type (frontend, backend) along with generator name in lightapi.net/codegen/listFramework/0.0.1

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#34]
The question is what type should we support? front, back or something else?

**Comment by NicholasAzar** [comment]
Database types as well maybe?

**Comment by stevehu** [comment]
Database dependency is supported in config.json and light-rest-4j generator now supports Oracle, Mysql and Postgresql. Also, H2 for test cases optional. What I can see now are front end and back end to categorize generators. It matches your UI as well.
