### ISSUE TITLE
mysql 8 implementing new authentification method "caching_sha2_password" 

### ISSUE THREAD

**Issue by NicolasFCO** [networknt/light-codegen#358]
Creating this handler: 

`public class RequestPostHandler implements LightHttpHandler {

    private static final DataSource ds = SingletonServiceFactory.getBean(DataSource.class);
    
    @Override
    public void handleRequest(HttpServerExchange exchange) throws Exception {
        Connection connection = ds.getConnection();
        exchange.getResponseHeaders().add(new HttpString("Content-Type"), "application/json");
        exchange.setStatusCode(405);
        exchange.getResponseSender().send("{}");

    }
}`

I get the following error:
`java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.`

This come from the version 8 of mysql which updated the authentication method from "mysql_native_password" to "caching_sha2_password".

[There is a post](https://stackoverflow.com/questions/50387952/how-to-resolve-unable-to-load-authentication-plugin-caching-sha2-password-issu)

**Comment by stevehu** [comment]
This seems like a MySQL specific issue. I am still using version 5.7 at the moment so I haven't encountered this issue yet. Looking into the MySQL document might find the answer.

**Comment by stevehu** [comment]
I am using mysql 8.0.12 and updating the mysql connector to mysql-connector-java-8.0.12 resolved the issue for me.

Hope it helps somebody.

**Comment by NicolasFCO** [comment]
I didn't try it (Possibly works). Another way to make it works is to disable the new authentication system and enable the old one. I did it in docker following this:  
https://github.com/docker-library/mysql/issues/454

Inserting this command in the docker-compose.yaml file:
`command: --default-authentication-plugin=mysql_native_password`

Thanks for the help
