### ISSUE TITLE
Update handler.yml template in Handler module to support audit on demand

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-codegen#370]
Generate the lighthttphandler.yml file.

Note: The YML takes the name of the file, as the handler module has also an additional handler.yml file for the corresponding Handler class; clear separation of functionality here.

**Comment by ddobrin** [comment]
Changes made in light-4j (#607) and light-rest-4j(#107) to add the properties in handler,yml and move AUDIT_INFO to AttachmentConstants

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update handler.yml template in Handler module to support audit on demand 1.6.x](https://trello.com/c/HrXkYo0M/442-update-handleryml-template-in-handler-module-to-support-audit-on-demand-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update handler.yml template in Handler module to support audit on demand master](https://trello.com/c/ysQuH0Ok/443-update-handleryml-template-in-handler-module-to-support-audit-on-demand-master)
