### ISSUE TITLE
generate enum with different annotation/description per enum value

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#372]
In normal case the enum define as below format:
        directDepositHandleType:
          type: string
          enum:
            - email
            - uuid
            - sms

And light-codegen will generate enum type with same name. 
public enum DirectDepositHandleTypeEnum {
    EMAIL, UUID, SMS
}

In some cases, user wants to generated enum type with different description as defined enum name. for example:
public enum DirectDepositHandleTypeEnum {
    EMAIL ("email type"),
    UUID("uuid type"), 
   SMS ("sms type");
}

We want to support several type of enum define:
1:
          enum:
            - email: email type
            - uuid:  uuid type
            - sms:  sms type
2:
          enum:
            - email {email type}
            - uuid { uuid type }
            - sms { sms type}

3:
          enum:
            - email (email type)
            - uuid ( uuid type )
            - sms ( sms type)

In OAI/OpenAPI-Specification, there are some discussion about it

https://github.com/OAI/OpenAPI-Specification/issues/348

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [generate enum with different annotation/description per enum value master](https://trello.com/c/l5cXU1im/440-generate-enum-with-different-annotation-description-per-enum-value-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [generate enum with different annotation/description per enum value 1.6.x](https://trello.com/c/9EjrGJrj/441-generate-enum-with-different-annotation-description-per-enum-value-16x)

**Comment by pedy711** [comment]
Hi, could you please provide an example of how to do this in OpenAPI Specification?
