### ISSUE TITLE
duplicated entries for {enableVerifyScope} in the openapiSecurity.yml.rocker.raw

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#378]
The enableVerifyScope item duplicated at generated openapi-security.yml file:

https://github.com/networknt/light-codegen/blob/1.6.x/light-rest-4j/src/main/resources/templates/rest/openapiSecurity.yml.rocker.raw

--- Enable JWT scope verification. Only valid when enableVerifyJwt is true.
enableVerifyScope: ${openapi-security.enableVerifyScope:true}

---  Enable JWT scope verification. 
--- Only valid when (enableVerifyJwt is true) AND (enableVerifyJWTScopeToken is true)
enableVerifyScope: ${openapi-security.enableVerifyScope:true}

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [duplicated entries for {enableVerifyScope} in the openapiSecurity.yml.rocker.raw 1.6.x](https://trello.com/c/yH4FZRMh/452-duplicated-entries-for-enableverifyscope-in-the-openapisecurityymlrockerraw-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [duplicated entries for {enableVerifyScope} in the openapiSecurity.yml.rocker.raw](https://trello.com/c/ZApc4BRK/453-duplicated-entries-for-enableverifyscope-in-the-openapisecurityymlrockerraw)
