### ISSUE TITLE
Codegen assumes existence of properties exists under ref:allOf in OpenAPI

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#386]
Codegen assumes existence of properties under ref:allOf. If it does not find a properties tag, it causes an error. However, the existence of a properties tag here is not a requirement of the OpenAPI spec.

E.g.: the following snippet would generate an error:

    BadResult400:
      type: object
      allOf:
      - $ref: '#/components/schemas/MyIdentifier'

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Codegen assumes existence of properties exists under ref:allOf in OpenAPI](https://trello.com/c/1jjocpP3/461-codegen-assumes-existence-of-properties-exists-under-refallof-in-openapi)
