### ISSUE TITLE
Generation of oneOf artifacts 

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-codegen#388]
This issue is related to: #386.

1. Codegen reaches TestResult400
2. It should generate an object TestResult400 with 2 elements: a StandardResponse and a ClientIdentifier
3. Note that there is no properties defined
4. The ClientIdentifier should be either a testID1 or testID2 object
5. when serializing the response, the toString() for the respective object should be called.

One implementation suggestion:
1. the ClientIdentifier is an interface and testID1 and testID2 implement that interface.
2. That allows the interface to be resolved to the underlying type of the object.

TestResult400:
      type: object
      allOf:
      - type: object
        properties:
          operationMetaData:
            $ref: '#/components/schemas/StandardResponse'
      - $ref: '#/components/schemas/ClientIdentifier'
    ClientIdentifier:
      description: just some text
      type: object
      oneOf:
      - $ref: '#/components/schemas/TestID1'
      - $ref: '#/components/schemas/TestID2'
...
    TestID1:
      type: object
      properties:
        id1:
          type: string
          maxLength: 15
          description: test
    TestID2:
      type: object
      properties:
        id2:
          description: test
          type: integer
          format: int64
          example: 911015108012

**Comment by ddobrin** [comment]
The code, as currently generated, and without properties set, is setting only the operationMetadata from above, and bypasses the oneOf:
...
public class TestResult400 {

    private StandardResponse operationMetaData;

    public TestResult400 () {
    }
...

**Comment by miklish** [comment]
Hi ddobrin. Given that (in the general case) the schemas under a oneOf can have arbitrarily different structures, how do you propose we create an interface that both implement? What methods signatures do you propose that (in your example) ClientIdentifier contain?

Also consider the following case:

ClientIdentifier:
description: just some text
type: object
oneOf:
- $ref: '#/components/schemas/TestID1'
- $ref: '#/components/schemas/TestID2'
…
BusinessIdentifier:
description: just some text
type: object
oneOf:
- $ref: '#/components/schemas/TestID1'
- $ref: '#/components/schemas/TestID3'

In this case, TestID1 must now implement both ClientIdentifier and BusinessIdentifier. How do you propose we handle this situation?

**Comment by miklish** [comment]
update: I see what you're saying... TestResult400 does not contain a reference the OneOf models... I don't think we can use interfaces in the short term, but we will at least add references to the resolved One of object in TestResult400.

**Comment by miklish** [comment]
We've continued to discuss this, and what we'd like to get from you is exactly (in full code) what Test400 should look like, as well as the full code for ClientIdentifier and TestID1, TestID2. Once we see what the ideal outcome you expect to see is, we can further investigate implementing this. Right now, we don't see how ClientIdentifier can be both an interface for both TestID1 and TestID2 in cases where TestID1 and TestID2 have different/incompatable properties. 

So it would be great to see what you have in mind here.

**Comment by ddobrin** [comment]
An abstract base class or interface, as suggested in my email via office email, would be the data element set in the Test400 class. 

The TestID1 and TestID2 would extend/implement and the main thing is to implement the toString(). By this, we could ensure that only classes extending/implementing the base are acceptable options for the oneOf and TestID1 and TestID2 would simply have a life of their own, with as many or as little dta elements as required

**Comment by ddobrin** [comment]
I can't build you the full set of classes right now, only tomorrow

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generation of oneOf artifacts 1.6.x](https://trello.com/c/9ZEHSzil/469-generation-of-oneof-artifacts-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generation of oneOf artifacts master](https://trello.com/c/m8eZoKGn/470-generation-of-oneof-artifacts-master)
