### ISSUE TITLE
service id out-of-sync since it is located two places

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#402]
When we generate API based on API specification and config.json, there are two places have service Id definition:

Server.yml:
serviceId: ${server.serviceId:com.networknt.marketsample-service-3.0.1}

And handler.yml (for health check):
  - path: '/health/com.networknt.marketsample-service-3.0.1'
    method: 'get'
    exec:
      - health

This could cause trouble if user change the service id in values.yml file or config server.
user may forget to change it from handler.yml. Then at the service deployment, consul will de-register the service since the health check failure.
Even user changed the handler.yml, the maven build use the codegen plugin may override the change and replace it with the default value.

I think we should change the codegen to use the injection token for service id in the handler.yml file. We need verify if this works or not.

**Comment by chenyan71** [comment]
@stevehu @ddobrin 
Can you please take a look and add comment on it?

**Comment by stevehu** [comment]
The serviceId is defined in the server.yml and it should be reused. The only thing that I am not sure of is if the template can be used as a partial string. If we can do the following, it would be just a little change in the light-codegen. 

```
path: '/health/${server.serverId}'
```
@jiachen1120 @BalloonWen Is the above doable?

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [service id out-of-sync since it is located two places master](https://trello.com/c/RZSLBR7A/499-service-id-out-of-sync-since-it-is-located-two-places-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [service id out-of-sync since it is located two places 1.6.x](https://trello.com/c/CJBicErE/500-service-id-out-of-sync-since-it-is-located-two-places-16x)
