### ISSUE TITLE
1.6.x release client.yml template missed important part

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#446]
Most of user still using JDK1.8 which need light-4j 1.6.x release.
The generated client.yml missed important config part for client request:
request:

  errorThreshold: ${client.errorThreshold:2}

  timeout: ${client.timeout:3000}

  resetTimeout: ${client.resetTimeout:7000}

  injectOpenTracing: ${client.injectOpenTracing:false}

  enableHttp2: ${client.enableHttp2:true}

  connectionPoolSize: ${client.connectionPoolSize:1000}

  maxReqPerConn: ${client.maxReqPerConn:1000000}

  maxConnectionNumPerHost: ${client.maxConnectionNumPerHost:1000}
 minConnectionNumPerHost

  minConnectionNumPerHost: ${client.minConnectionNumPerHost:250}

**Comment by stevehu** [comment]
Done.
