### ISSUE TITLE
change default handler chain sequence for audit handler

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#497]
audit handler should be in an upper position, at least above JwtVerifyHandler
including all the three frameworks

the default chain will be:
```
    - exception
    - metrics
    - traceability
    - correlation
    - body
    - audit
    - specification
    - security
    - dump
    - sanitizer
    - validator
   ```

**Comment by stevehu** [comment]
This is to enable the error status response from the JwtVerifierHandler to show up in the audit log for security monitoring. @miklish @jiachen1120 Please talk to your client to see if this is an acceptable change. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [change default handler chain sequence for audit handler light-codegen master](https://trello.com/c/LlRrzndU/909-change-default-handler-chain-sequence-for-audit-handler-light-codegen-master)
