### ISSUE TITLE
Macos Windows build failure due to caSe sensitive file name App.java and app.java by Rocker

### ISSUE THREAD

**Issue by PeterKieu** [networknt/light-codegen#519]
This issue is by Rocker module, it generates app.java and App.java in the same folder generated-src/rocker/main/templates/lambda.

Building on Linux is ok, but 2 files are generated app.java and App.java with same content, only differ from app vs App.

Building Windows and default MacOS (Big Sur x86) file system do not use case-sensitive file name: 
- On Windows: the generated file is App.java and the class name is app{}
- On MacOS Big Sur x86: the generated file is app.java and the class name is App{}

Solution 1: Use one file and Fix matching file name and class name => Re-build faces the issue again :)  
Solution 2: Debug from Rocker lib or template file

**Comment by stevehu** [comment]
I think this has been reported by one of our users and fixed in the master branch. Could you please try the master branch instead of the default release branch?

**Comment by PeterKieu** [comment]
Master branch fixed!

Thanks much Steve!
