### ISSUE TITLE
give users an option to use Gradle vs Maven

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#540]
buildMaven is the parameter in the config.json or config.yaml to control if Maven is used or Gradle is used. The default is false which means the Gradle is the default.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [give users an option to use Gradle vs Maven light-codegen master](https://trello.com/c/gbXR2BQ8/965-give-users-an-option-to-use-gradle-vs-maven-light-codegen-master)

**Comment by PeterKieu** [comment]
Thanks for the grable build option.
However, I checked out the new codegen and give a try (cli + rest) but the default build is still maven, not gradle:
java -jar ./codegen-cli.jar -f openapi -o $OUTPUT -m $MODEL_OPENAPI -c $CONFIG

I am traveling the source code to find more.
I faced many issues when building with gradle, specially with Kafka libs, then I want to share on gradle Rock templates.

**Comment by PeterKieu** [comment]
Sorry. I used the Release branch while gradle is not the Master.

**Comment by stevehu** [comment]
We are going to generate multiple modules for the project as this is required by our customers. The model can be shared by both server and client. The service is what developers want to focus on.

**Comment by PeterKieu** [comment]
Oh, that is the point! We share models and asign services to team members.
