### ISSUE TITLE
model module is not creating directory based on package name

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#554]
when generating multiple module, the model module doesn't have the correct path.
eg. model/src/main/java/Pet.java, which should be model/src/main/java/com/networknt/Pet.java

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [model module is not creating directory based on package name light-codegen master](https://trello.com/c/u7ZV5IMe/979-model-module-is-not-creating-directory-based-on-package-name-light-codegen-master)
