### ISSUE TITLE
json property is missing for enum types

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#557]
e.g. the current generated enum doesn't have json properties, which will cause error when use jackson for deserialization
```
    public enum StatusEnum {
        
        AVAILABLE ("available"), 
        
        SOLD ("sold"), 
        
        PENDING ("pending"); 
```
should add json property for serialize and deserialize 
```
    public enum StatusEnum {
        
        @JsonProperty("available")
        AVAILABLE ("available"), 
        
        @JsonProperty("sold")
        SOLD ("sold"), 
        
        @JsonProperty("pending")
        PENDING ("pending"); 
```

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [json property is missing for enum types light-codegen master](https://trello.com/c/yxvQIKot/1000-json-property-is-missing-for-enum-types-light-codegen-master)
