### ISSUE TITLE
portalRegistry healthpath duplicated serviceId

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/light-codegen#595]
The raw file for portal registry: protalRegistryYml.rocker.raw defile healthPath:

healthPath: ${portalRegistry.healthPath:/health/@serviceId}

But in the light-controller, the health check  path will add service id for health path:

send(connection, Methods.GET, **healthPath + serviceId**, config.getBootstrapToken(), null);

Which cause the error below:

 {"statusCode":404,"code":"ERR10048","message":"PATH_NOT_IMPLEMENTED","description":"No handler defined for path '/health/com.networknt.petstore-3.0.1com.networknt.petstore-3.0.1'","severity":"ERROR"}

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [portalRegistry healthpath duplicated serviceId light-4j master](https://trello.com/c/WSXDeGgc/1237-portalregistry-healthpath-duplicated-serviceid-light-4j-master)
