### ISSUE TITLE
https://doc.networknt.com/tool/light-codegen/download-build/ - doesn't clean build

### ISSUE THREAD

**Issue by Johnlon** [networknt/light-codegen#621]
Downloaded from central: https://oss.sonatype.org/content/repositories/releases/org/junit/jupiter/junit-jupiter-params/5.8.1/junit-jupiter-params-5.8.1.jar (576 kB at 404 kB/s)
Downloaded from central: https://oss.sonatype.org/content/repositories/releases/org/junit/platform/junit-platform-engine/1.8.1/junit-platform-engine-1.8.1.jar (186 kB at 126 kB/s)
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ codegen-core ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (pre-unit-test) @ codegen-core ---
[INFO] surefireArgLine set to -javaagent:/home/john/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/john/work/github/light-codegen/codegen-core/target/jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ codegen-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/john/work/github/light-codegen/codegen-core/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ codegen-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/john/work/github/light-codegen/codegen-core/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Parent POM 2.1.0:
[INFO]
[INFO] Parent POM ......................................... SUCCESS [  2.763 s]
[INFO] codegen-core ....................................... FAILURE [  9.957 s]
[INFO] light-rest-4j-generator ............................ SKIPPED
[INFO] light-hybrid-4j-generator .......................... SKIPPED
[INFO] light-graphql-4j-generator ......................... SKIPPED
[INFO] codegen-fwk ........................................ SKIPPED
[INFO] codegen-cli ........................................ SKIPPED
[INFO] codegen-web ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.427 s
[INFO] Finished at: 2022-03-12T20:25:34Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project codegen-core: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :codegen-core

**Comment by stevehu** [comment]
I just build from the master and the default release branch. Both branches are built OK. Are you sure you are using Java 11 to build?
