### ISSUE TITLE
Find a standard way to serve single page application from light-*-4j framework

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#66]
In development, we normally use node to serve the single page application and proxy API request to the light-*-4j server. On production, it is much easier to serve SPA from the API server so that we don't need to config CORS middleware on the API server and save an instance of Node. 

We are using this issue to track all the ideas on how we can standardize the config and folder structure.

**Comment by NicholasAzar** [comment]
@stevehu not sure if this is the right place to discuss this, but it reminded me.. have you checked out https://github.com/zalando/tailor as a way to compose fragments of ui served from domain specific microservices? Especially important if smaller domain specific teams want to alleviate dependencies on other teams in the same application.
However I do realize that there will be some use cases where having a single microservice respond with the whole webpage will be required.

**Comment by stevehu** [comment]
This is a very popular approach to compose UI these days although it is very early. In the light-portal project, I do want to try it out but it need a lot of work on the UI for the layout and communication between components. There is one thing that the industry is still not catching up is the HTTP 2.0 as light-4j supports it natively. There are a lot of webpack tasks doesn't make sense anymore if the api server supports HTTP 2.0. I am starting to look into the light-portal as of today and focus on it for the next couple of weeks.

**Comment by stevehu** [comment]
With light-router in the picture and the resource handler in light-4j, we encourage users to use light-router to serve the SPA without CORS as the services are in the same router. Here are several tutorials that can help users get started.
