### ISSUE TITLE
Allow codegen to generate code without security definitions being required

### ISSUE THREAD

**Issue by ericbroda** [networknt/light-codegen#82]
When a simple swagger specification is provided -- one without security definitions -- then the generator will emit an error stating that security definitions are required. 

This leads to a simple problem:  one cannot create the prototypical "hello world" API, one that is simple to understand by virtue of it not being encumbered with extra complexity.  This is a gap in our capability.

Security definitions should not be mandatory, but optional, perhaps with a "--secure" flag that when provided the generator will check for this requirement, and when not present, it will not check for this.

**Comment by stevehu** [comment]
@ericbroda Design driven and security first are the fundamental principles for light-*-4j frameworks as our target are enterprise customers. Swagger is a very flexible specification that can accommodate both design driven or reverse engineering from the source code. It cannot apply restrictions on either side; however, we are using swagger as our entry point to scaffold project and we have the luxury to enforce standard in our light-codegen to give users narrowed spec adoptions and best practices. This also eliminates some shortcomings of swagger-codegen like the generated model name with body, body1, body2 etc. Also, if you look at examples on the Internet, it is very hard to find any spec without security as the nature of the API requires protection more than any other type of the applications.
