### ISSUE TITLE
Following docs to generate code openapi scaffolding

### ISSUE THREAD

**Issue by gonzalovazquez** [networknt/light-codegen#91]
Hi Steve,

I wrote a simple Open API spec and I am using light-codegen to generate my project however I get the following error: **Invalid framework light-rest-4j**

When I follow the documentation and I run the sample swagger.json I also get the same error.

https://doc.networknt.com/tutorial/generator/openapi/

`java -jar codegen-cli/target/codegen-cli.jar -f light-rest-4j -o /tmp/gen -m light-rest-4j/src/test/resources/swagger.json -c light-rest-4j/src/test/resources/config.json`

**Comment by stevehu** [comment]
@gonzalovazquez As of release 1.5.4, we have OpenAPI 3.0 support in light-rest-4j along with Swagger 2.0 support. In order to differenciate these two incompatible implementations, we have change the framework name from light-rest-4j to swagger and openapi. In your command line, you are using swagger.json as input so the framework name should be "-f swagger". Also, the following updated tutorials might help. https://doc.networknt.com/tutorial/rest/

**Comment by gonzalovazquez** [comment]
Hi Steve, 

Thank you for your response. I now get a different error.
```
java.lang.NullPointerException
        at com.networknt.codegen.rest.OpenApiGenerator.injectEndpoints(OpenApiGenerator.java:308)
        at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:126)
        at com.networknt.codegen.Cli.run(Cli.java:65)
        at com.networknt.codegen.Cli.main(Cli.java:39)
```

I tried with my openapi spec, as well as with a sample petstore that follows the Open API 3.0 spec, however both give me the same error. This is the command I am running:

```
 java -jar light-codegen/codegen-cli/target/codegen-cli.jar -f openapi -o ~/Projects/Chores -m ~/Downloads/openapi.json -c ~/Downloads/config.json
```

I do see most of the scaffolding after the error expect for the handler directory.

I have attached the openapi spec I am testing with.

Thank you,
Gonzalo
[openapi.json.zip](https://github.com/networknt/light-codegen/files/1502791/openapi.json.zip)

**Comment by stevehu** [comment]
The following section shouldn't be there as the codegen doesn't know how to create a model out of array. In Java, array should be modelled as collection of pet so pet class needs to be generated. The one you have attached is the original example and I have modified it to work with our light-codegen. The updated version can be found at https://github.com/networknt/model-config/tree/master/rest/openapi/petstore/1.0.0 and it works. 

```
      "Pets": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Pet"
        }
      },
```

**Comment by stevehu** [comment]
Someone in gitter room has confirmed that this tutorial works. 

https://doc.networknt.com/tutorial/rest/openapi/petstore/

**Comment by gonzalovazquez** [comment]
Thank you Steve!
